### ISSUE TITLE
Support overrides style with MUI Theme

### ISSUE THREAD

**Issue by suiaing** [Yuvaleros/material-ui-dropzone#125]
Instead of makeStyles/useStyles to apply the style to apply the style class to component only, can dropzone support overrides style with MUI Theme globally?

https://material-ui.com/styles/api/#withstyles-styles-options-higher-order-component

**Comment by reckter** [comment]
This would be very awesome!
Right now when styling for a dark mode, there is no way to recreate the stripes, because we can not select the `dropActive` styling. Using the theme directly from material-ui would solve this problem :) (probably `palette.background.default` and `palette.background.paper` or something similar)
