### ISSUE TITLE
Release changelog

### ISSUE THREAD

**Issue by mattcorner** [Yuvaleros/material-ui-dropzone#136]
Might I suggest a changelog for this package? It is hard to keep track of what features are updated etc. I just had to go through the pull requests to find out what was changed in the latest release, and find that a breaking change wasn't even highlighted. 

A CHANGELOG.md file, or making use of the releases tab would be great. 

Thanks for the work!

**Comment by panz3r** [comment]
Hi @mattcorner ,

Thanks for your feedback and sorry for the delay in this answer.

> I just had to go through the pull requests to find out what was changed in the latest release, and find that a breaking change wasn't even highlighted.

Regarding the breaking change it's not published as of yet on NPM and will be released as version `3.0` to highlight the backward-incompatible changes 😉 .

> A CHANGELOG.md file, or making use of the releases tab would be great.

I just added a `CHANGELOG.md` file to both `master` and `v2.x` branch, they are quite similar but need to be differentiated because on `master` we are developing version `3.x` whilst keeping `v2.x` updated on its dedicated branch.

In the coming days I'll look into adding some Release and tags to keep better track of the changes on Github.

Thanks again and let me know what do you think about the files, any suggestion is really appreciated.

**Comment by mattcorner** [comment]
Thanks @panz3r, looks good.

I'd suggest its slightly confusing that master isn't the latest release so the changelog shows me the things that aren't available yet, but that's just me being picky 😄. 

Important thing is that its now easy to see what's changed 👍

**Comment by panz3r** [comment]
Hi @mattcorner ,

Thanks for your feedback again.

I just completed updating the `Release` tab with only the published versions.


> I'd suggest its slightly confusing that master isn't the latest release so the changelog shows me the things that aren't available yet, but that's just me being picky

I'm thinking about adding a new action to automate the release process a bit but it will take some time to be operational (I'd also like to close some more issues first).

Thanks again, I'm closing this issue.
