### ISSUE TITLE
DropzoneDialog preview image sizing on small screens

### ISSUE THREAD

**Issue by WJ89** [Yuvaleros/material-ui-dropzone#165]
### Describe the bug
On mobile sized screens the preview image(s) get distorted due to being forced into the xs-4 grid
 
### Expected behavior
Image stays at correct ratio, perhaps full width on small screens?

### Screenshots
![image](https://user-images.githubusercontent.com/9322140/81766139-e3b0f400-9518-11ea-9805-234bdbb10851.png)

**Comment by WJ89** [comment]
Realised previewGridProps was a thing, never mind!

previewGridProps={{container: {spacing: 5}, item: {xs: 6}}}

**Comment by max-carroll** [comment]
I don't think this issue is fixed perhaps we should actually make the component responsive?

e.g. xs={12} md={4} at least ? we should have a play around with it and make it look good on all devices, we should also perhaps consider do we really want a default spacing of 8, seems to cause more problems than it solves perhaps?

**Comment by panz3r** [comment]
Hi @WJ89 ,

Thanks for your feedback, actually the "Preview" section is getting a lot of attention in the last period so we're going to improve it a bit (or we hope so 😅 ).
You can follow the development and contribute with your ideas/feedbacks on this issue #166 .

@max-carroll  Opened the above issue to further discuss how to proceed with the "Preview" section.
