### ISSUE TITLE
Props are not passed to react-dropzone

### ISSUE THREAD

**Issue by thminggg** [Yuvaleros/material-ui-dropzone#195]
### Describe the bug - 
trying to pass [props](https://react-dropzone.js.org/#src) via `dropzoneProps` stated in [documentation](https://yuvaleros.github.io/material-ui-dropzone/), but found the props are not passed down to the `react-dropzone`

### Steps to reproduce

`<DropzoneArea onChange={onDropzoneChange} showAlerts={false} dropzoneProps={{multiple: false}} />`

### Expected behavior
expect to see the props (i.e. `multiple` in the above example) to be passed to `react-dropzone`
### Versions

- OS: MacOS
- Browser: Chrome
- `@material-ui/core` version: 4.9.3
- `material-ui-dropzone` version: 2.4.8

**Comment by panz3r** [comment]
Hi @thminggg ,

Thanks for your feedback, the prop you are trying to set is actually managed by `material-ui-dropzone` when setting the `filesLimit` prop, to achieve what you want set `filesLimit` to `1`.

**Comment by thminggg** [comment]
I see. Thanks for the great comment.

So back to the origin of this issue, the function being passed to the `material-ui-dropzone`‘s `dropzoneProps` is not passed to the `react-dropzone` component successfully.

May I know is there anything I didn’t handle well?

**Comment by panz3r** [comment]
Hi @thminggg ,

Can you please post the code that's causing you trouble?

The `onDropAccepted` and `onDropRejected` are currently being overridden by `material-ui-dropzone` in order to work correctly, you can know when files are dropped/removed from the dropzone using the `onChange` and `onDelete` callback of the `DropzoneArea` component.

**Comment by thminggg** [comment]
Hi @panz3r, 

Thanks for the reply.

Because the `onChange` of the `material-ui-dropzone` doesn't have a callback when the file is fully loaded into the dropzone (i.e. the preview is shown completely & all dropped in files are recognised)

Please check below observation

By observation, here is what happened:

1. dropped 2 files into the dropzone (i.e. one small size photo & one large size video)
2. first small size photo loaded in dropzone immediately
3. second large size video (i.e. ~430MB) loaded in dropzone after few seconds

As a result, `onChange` is called **twice** while I have **no way to know whether the files are fully loaded or not.**

<img width="595" alt="image" src="https://user-images.githubusercontent.com/17175914/84937497-6deb0a00-b10e-11ea-8f0b-0fac139099c6.png">


Given that, I was checking whether `onDropAccepted` & `onDropRejected` can be the callbacks I can use to check whether the files are fully loaded or not.

However, I found the function (i.e. `filesFullyLoaded`) I passed to `dropzoneProps` is not passed down to the `react-dropzone`

`<DropzoneArea 
      onChange={onDropzoneChange} 
      dropzoneProps={{
          onDropAccepted={filesFullyLoaded}
          onDropRejected ={filesFullyLoaded}
      }} 
/>`

Thus, would like to have your kind help to see if I am passing the wrong way?

**Comment by panz3r** [comment]
Hi @thminggg ,

Thanks for providing more details, now I think to know where the issue is.

> Because the onChange of the material-ui-dropzone doesn't have a callback when the file is fully loaded into the dropzone

Actually the `onChange` callback is invoked for each changes to the files array after the file has been read (this is done to show the correct preview), to be notified as soon as a file is dropped you can use the `onDrop` callback prop.

> Thus, would like to have your kind help to see if I am passing the wrong way?

Unfortunately the `onDropAccepted` and `onDropRejected` cannot be passed to `react-dropzone` because are required by `material-ui-dropzone` to work as expected.

I can suggest you to try to use the `onDrop` callback (which is invoked as soon as the file is dropped) and the `onChange` one (invoked when the file as been loaded and is visible in the preview) and see if that helps you with your implementation.

**Comment by thminggg** [comment]
Hi @panz3r,

thanks so much for the comment and I'm so sorry for such a late reply.

Got your point that the callback is reserved for the package, and I'm currently looking into the `react-dropzone` to try resolve the issue here.

really appreciate for the great help and looking forward to the package development!
