### ISSUE TITLE
Unable to press submit button once all the files are deleted

### ISSUE THREAD

**Issue by sanals** [Yuvaleros/material-ui-dropzone#217]
1. Create a DropzoneDialog
  2. Add few images and save them to database. Load them back again to DropzoneDialog when reopening for editing(adding /removing).
  3. Remove all images. I am not able to click submit button for DropzoneDialog, because its disabled and not able to re-enable it. 
  
![ezgif com-crop](https://user-images.githubusercontent.com/16471631/88080011-1bcd5680-cb9c-11ea-8280-879d0f219048.gif)

**Comment by panz3r** [comment]
Hi @sanals ,

The described behaviour is actually the expected one for this module since it should be used as an Input and not as a file management component.

**Comment by mkarajohn** [comment]
Can we reopen this issue? Not being able to submit is *noot* expected behaviour.

I have a usecase where whatever the user does inside the modal is just temporary, and in order for the data to actually pass to the form, they need to click on the Submit button.

The user can later reopen the modal in case they want to remove one (or all) of the files and upload different ones.

Not being able to click the button once all the files have been removed effectively forbids the user to edit his uploaded files.

@panz3r
