### ISSUE TITLE
Property to Change the Dropzone Icon

### ISSUE THREAD

**Issue by N4Design** [Yuvaleros/material-ui-dropzone#48]
How do I change the icon to use the CloudUploadOutlined icon in the dropzone for consistency within my app? Maybe introduce a prop for it?

**Comment by Yuvaleros** [comment]
What would you think would be a good solution here? a property that receives a path? or maybe it should receive a Material UI icon component?

**Comment by HaswinVidanage** [comment]
+1 on Material UI icon

**Comment by max-carroll** [comment]
well you could have it passed in as a prop, and because you will want to set the classes on it you can probably pass those in as props using React.createElement

const icon = React.createElement(this.props.customIcon, { className: classes.uploadIconSize }); |

and have the default props as CloudUploadIcon , just an idea,

**Comment by panz3r** [comment]
Hi @max-carroll ,

Thanks for your suggestion, currently there's an open PR #110 implementing this feature as you suggested.

I'll review it as soon as possible.

**Comment by max-carroll** [comment]
Ahh I've already implemented it on my side, didn;t realise that 🤣, ill review
