### ISSUE TITLE
initialFiles not shown up 

### ISSUE THREAD

**Issue by ameenazeemiacmedocs** [Yuvaleros/material-ui-dropzone#87]
I am getting an issue on Initial Files do not show up  ,it shows like 
![image](https://user-images.githubusercontent.com/40419995/69325802-8ecca900-0c6c-11ea-9d8f-4188f8ee83dd.png)

instead of actual image. Below is the code that i am using 

`<DropzoneArea
                                            acceptedFiles={['image/jpeg', 'image/png', 'image/bmp']}
                                            showPreviews={true}
                                            showPreviewsInDropzone={true}
                                            showFileNamesInPreview={true}
                                            initialFiles={[`https://images.pexels.com/photos/1909603/pexels-photo-1909603.jpeg`]}
                                            filesLimit={1}
                                            maxFileSize={1000 * 1000}
                                            dropzoneText="Advertisement Image"
                                            onChange={changeAdImage}

                                        />`

**Comment by lahoti-piyush** [comment]
i am also facing some issue.

**Comment by brizandrew** [comment]
I think I've figured out the problem. It looks like the ternary that decides whether to show a real image or this icon uses [this helper function](https://github.com/Yuvaleros/material-ui-dropzone/blob/master/src/helpers/helpers.js#L1-L7).

That function is returning "false" incorrectly on your image and mine because [this other helper function](https://github.com/Yuvaleros/material-ui-dropzone/blob/master/src/helpers/helpers.js#L21-L28) is adding an extension even if the file has one in the URL. 

For example your file is being named `pexels-photo-1909603.jpeg.jpg` by `createFileFromURL` and then `isImage` is saying `jpeg.jpg` is not a valid image extension. 

I'm not sure what the best solution here is, maybe checking to see if the filename already has an extension before adding it.

**Comment by seanhaufler** [comment]
This logic change to the `isImage` function worked for me, feel free to use / submit a pull request if you like:

```
export function isImage(file) {
    const fileName = file.name || file.path;
    const match = /.*\.(.+)/.exec(fileName)
    if (!match || match.length < 2) {
        return false
    }
    const suffix = match[1]
    if (suffix === 'jpg' || suffix === 'jpeg' || suffix === 'bmp' || suffix === 'png') {
        return true;
    }
    return false
}
```

**Comment by Rambalac** [comment]
Image does not need to have any extension to be an image.

**Comment by faupol3** [comment]
Fix at https://github.com/Yuvaleros/material-ui-dropzone/pull/101

**Comment by s8990** [comment]
initialFiles not work 
see this link :
https://codesandbox.io/s/material-ui-dropzone-initialfiles-qww1z
