### ISSUE TITLE
Clear dropzone after api call 

### ISSUE THREAD

**Issue by william-levi** [Yuvaleros/material-ui-dropzone#9]
How to reset/clear dropzone after a function call or api call.

**Comment by jackpilowsky** [comment]
Currently, the only way to do this is to have the component unmount from the page. 

I'm working on a pull request for this, but it might be sometime before it becomes available.

**Comment by JaredDiCioccio** [comment]
Would love this feature as well.

**Comment by Piccirello** [comment]
A quick + dirty workaround is to assign the `DropzoneArea` a numeric `key` that you increment after your API call. The new key will force React to re-render the component, resulting in its state being cleared.

**Comment by qlecler** [comment]
> A quick + dirty workaround is to assign the `DropzoneArea` a numeric `key` that you increment after your API call. The new key will force React to re-render the component, resulting in its state being cleared.

Any way to clear it directly?

**Comment by Piccirello** [comment]
Not that I’ve found. I think a PR may be necessary.

**Comment by jboxxx** [comment]
Piccirello's solution is quite serviceable for now.  Thank you

**Comment by dmbarry86** [comment]
I would like this feature as well. Currently using the workaround suggested by Piccirello.

**Comment by wesdean** [comment]
I added a key to DropzoneArea and it is still not clearing the drop zone. Can someone post an example of how to get this to work?

**Comment by acabreragnz** [comment]
![Screenshot from 2020-04-27 21-26-34](https://user-images.githubusercontent.com/6330366/80433618-cf8cb600-88cd-11ea-9df3-097dfaac177a.png)

The workaround mentioned in this thread doesn't work any more, look at the error above, plus this I cannot add many files at once.

I've used a debounced key
```
  const [debounceKey] = useDebounce(key, 500);
```

**Comment by comilao** [comment]
> ![Screenshot from 2020-04-27 21-26-34](https://user-images.githubusercontent.com/6330366/80433618-cf8cb600-88cd-11ea-9df3-097dfaac177a.png)
> 
> The workaround mentioned in this thread doesn't work any more, look at the error above, plus this I cannot add many files at once.
> 
> I've used a debounced key
> 
> ```
>   const [debounceKey] = useDebounce(key, 1);
> ```

Just to add a bit, `useDebounce` is this [npm package](https://www.npmjs.com/package/use-debounce).
A simple sample with dropzone would be like this:
```
const [key, setKey] = useState(0);
const [debounceKey] = useDebounce(key, 1000);

<DropzoneArea key={debounceKey}>
```
use `setKey()` to force React to re-render the component

**Comment by codejedi365** [comment]
> ![Screenshot from 2020-04-27 21-26-34](https://user-images.githubusercontent.com/6330366/80433618-cf8cb600-88cd-11ea-9df3-097dfaac177a.png)
> 
> The workaround mentioned in this thread doesn't work any more, look at the error above, plus this I cannot add many files at once.
> 
> I've used a debounced key
> 
> ```
>   const [debounceKey] = useDebounce(key, 1);
> ```

@acabreragnz, It is important to note that the likely reason you are actually getting this error is not because of the failure of `setKey()` or `useDebounce()`.  The error you received happens because when you change the state synchronously, the render is processed before the secondary internal effects of `react-dropzone` have completed.

`React-dropzone` and especially `material-ui-dropzone` enable events such as snackbar alerts, or the file preview render which haven't completed yet when you are forcefully unmounting the `<DropzoneArea />` component.

Recommend instead wrapping your `setKey()` in a "run on nextTick()" function:
```js
// Cross-Browser safe version of (process.nextTick() & setImmediate())
window.setTimeout(() => {
  setKey()
}, 0)
```
This will wait for all async tasks to complete before unmounting the component which will prevent the "memory-leak" error but still run a unmount() and remount() which still maintains the intended functionality of resetting/clearing uploaded files in `<DropzoneArea />`.
