### ISSUE TITLE
Processing of file data & inquire about current project status

### ISSUE THREAD

**Issue by Ordinateur-Hack** [Yuvaleros/material-ui-dropzone#93]
Hello everybody,

thanks to every contributor for this amazing project. I just wanted to inquire about the current status of the material-ui-dropzone due to the fact that the underyling react-dropzone is now available as npm package version 10.2.1, however we are still using version 7 here. Are there any reasons why not to upgrade the codebase, especially with newly introduced hooks?

And just one more question/suggestion referring to DropzoneArea:
https://github.com/Yuvaleros/material-ui-dropzone/blob/063a84132db08624cd6181d7cc8cfb19da24203e/src/DropzoneArea.js#L113-L124
Here we just pass an array of `fileObject.file` to the `onChange(files)` method specified in the props `this.props.onChange(...)`. In line 117 we saved `event.target.result` in the `data`-key. However, where do we actually need this; at least in the `DropzoneArea.js`-file we don't read the data anywhere. According to MDN the `result` attribute [contains the data as a data: URL representing the file's data as a base64 encoded string.](https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsDataURL), but why do we save this if we don't process it?

Originally, I came across this because I tried to access the files content (not only its metadata) when the user uploads it using the dropzone. That's why I encountered the `data`-key in `fileObjects.` Referring to the [File interface](https://developer.mozilla.org/en-US/docs/Web/API/File), I figured out that we can use the `arrayBuffer()` method that `File` inherits from `Blob`. Maybe we can add a hint to our docs, so that newcomers like me learn right away how to process the files content?

**Comment by panz3r** [comment]
Hi @Ordinateur-Hack ,

Thanks for your feedback, I'll try to answer your questions below.

>  I just wanted to inquire about the current status of the material-ui-dropzone due to the fact that the underyling react-dropzone is now available as npm package version 10.2.1, however we are still using version 7 here.

This has been done as part of the work on version `3.0` which is now based on `react-dropzone` `10.x`, a "legacy" version (based on `react-dropzone` `9.x` and `react` `15.x`) is also available on the `v2.x` branch.

A future version based on `react-dropzone` `11.x` is also expected (might be `4.x` or `5.x`, we'll see 😬 ).

> Are there any reasons why not to upgrade the codebase, especially with newly introduced hooks?

There has been some work on this too and is expected to be shipped later on (a PR is currently open with the migration of this module code to also use `hooks` internally - see PR #144 for more details).

> And just one more question/suggestion referring to DropzoneArea

Since the refactoring for version `3.x` the code you posted is a bit outdated, if you still see issues with the latest version of this module please open a new issue.

Thanks again for your feedback and sorry for the delayed answer.
